name: Python
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[test]"
        env:
          DISTUTILS_USE_SDK: 1
          MSSdk: 1
      - name: Run the unit tests
        run: python -m pytest --cov celerite2 python/test
      - name: Coveralls
        if: startsWith(matrix.os, 'ubuntu')
        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          parallel: true
          flag-name: Unit Tests

  pymc3:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[test,pymc3]"
      - name: Get theano compiledir
        id: compiledir
        run: |
          python -c "import theano; print('::set-output name=compiledir::' + theano.config.compiledir.split('/')[-1])"
      - name: "Cache ~/.theano"
        uses: actions/cache@v2
        with:
          path: ~/.theano
          key: theano-${{ steps.compiledir.outputs.compiledir }}-${{ hashFiles('python/test/theano/*.py') }}
          restore-keys: |
            theano-${{ steps.compiledir.outputs.compiledir }}-
            theano-
      - name: Run the unit tests
        run: python -m pytest --cov celerite2 python/test/theano
      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          parallel: true
          flag-name: Unit Tests

  jax:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          auto-update-conda: true
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip install --use-feature=2020-resolver -e ".[test,jax]"
      - name: Run the unit tests
        shell: bash -l {0}
        run: python -m pytest --cov celerite2 python/test/jax
      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          parallel: true
          flag-name: Unit Tests

  coverage:
    needs: [build, pymc3, jax]
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          parallel-finished: true
